[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.towncrier]
    name = "ATT&CK website"
    version = "3.6.4"
    filename = "CHANGELOG.md"
    issue_format = "[#{issue}](https://github.com/mitre-attack/attack-website/issues/{issue})"
    template = ".towncrier.template.md"
    start_string = "<!-- TOWNCRIER -->\n"
    title_format = "# {name} {version} ({project_date})"
    underlines = ["-", "", ""]
